POST http://localhost:3000/api/login
Content-Type: application/x-www-form-urlencoded

email=ifexcojerry4ril@gmail.com
&password=12345678

###
GET http://localhost:3000/api/info/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Mjk3ZjE0NDg0Y2NkMDJhN2NiMjI1NDYiLCJ1c2VyIjp7ImVtYWlsVmVyaWZpZWQiOnRydWUsImFzc2Vzc21lbnRSZXNwb25zZSI6dHJ1ZSwiYWNjb3VudFZlcmlmaWVkIjpmYWxzZSwiYWRkcmVzc1ZlcmlmaWVkIjpmYWxzZSwibGVnYWxBZ3JlZW1lbnQiOmZhbHNlLCJfaWQiOiI2Mjk3ZjE0NDg0Y2NkMDJhN2NiMjI1NDYiLCJmdWxsbmFtZSI6IkplcnJ5IFdlYm1hbiIsInBob25lIjowLCJvY2N1cGF0aW9uIjoiRGV2ZWxvcGVyIEFkdm9jYXRlIiwic3RyZWV0IjoiIiwiY2l0eSI6IiIsImNvdW50cnkiOiIiLCJkYXRlT2ZCaXJ0aCI6IjA4LWZlYi0yMDIyIiwicGluIjoiIiwidmVyaWZ5Q29kZSI6bnVsbCwiZW1haWwiOiJpZmV4Y29qZXJyeTRyaWxAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkT0RqQURmSTRTY3VKY0l2VzZnSTNBZTNNVkFBenRZSUlUYURiUFYuNmlveWFyWVpwQ3pTSmEiLCJkYXRlSm9pbmVkIjoiMjAyMi0wNi0wMVQyMzowNzo0OC4zMDNaIiwiX192IjowfSwiaWF0IjoxNjU0NTYwMDgzNDkwLCJleHAiOjE2NTQ1NjAwODM1MDV9.oL_XU9YFiaP1oe5s5uCLDu3_36dP3CdyfxawJu3YPbs

###
DELETE http://localhost:3000/logout

